# Generated by Django 3.2.3 on 2021-12-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20211201_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='EE', max_length=100),
            preserve_default=False,
        ),
    ]
